stages:
  - move
  - build
  - deploy
  

build:
  stage: build
  script:
    - echo "Building the application on SSH server..."
    - hostname
    - pwd
    - ssh wallet  "mkdir -p  /home/ahdev/application/wallet-dev/ && cd /home/ahdev/application/wallet-dev/ && chmod +x ./gradlew && ./gradlew clean && ./gradlew build -x test"

    - echo "Source code built on remote server"
  only:
    - dev


move:
  stage: move
  script:
    - echo "Copying  from remote server to GitLab CI/CD..."
    - hostname
    - pwd


    - ssh wallet "rm -rf /home/ahdev/application/wallet-dev/*"

    - scp -o StrictHostKeyChecking=no   -r ./*  wallet:/home/ahdev/application/wallet-dev/ 


    - echo "Artifacts uploaded to GitLab CI/CD."
  only:
    - dev

deploy:
  stage: deploy
  script:
    - hostname
    - pwd
    - ssh wallet "docker --version && docker rm wallet-dev && docker ps -q -f name=wallet-dev | grep -q . && docker  stop wallet-dev || true && docker rm wallet-dev || true && docker run -d --name wallet-dev -p 8081:8081 wallet-dev:latest"
  only:
    - dev 


