stages:
  - move
  - build

build:
  stage: build
  script:
    - echo "Building the application on SSH server..."
    - hostname
    - pwd
    - ssh -p 22 david@172.26.0.41  "mkdir -p cd /home/david/application/wallet-dev/ && cd /home/david/application/wallet-dev/ && chmod +x ./gradlew && ./gradlew clean && ./gradlew build -x test"
    - echo "Source code built on remote server"
  only:
    - main

move:
  stage: move
  script:
    - echo "Copying  from remote server to GitLab CI/CD..."
    - hostname
    - pwd
<<<<<<< HEAD
    - scp -o StrictHostKeyChecking=no   -P 22 -r ./*  david@172.26.0.41:/home/david/application/wallet-dev/ 
=======
    - scp  -v  -P 22 -r ./*  david@172.26.0.41:/home/david/application/wallet-dev/ 
>>>>>>> de929d6b0e53270869f00229ce107e3b3edc5b35
    - echo "Artifacts uploaded to GitLab CI/CD."
  only:
    - main
