spring.datasource.url=jdbc:mysql://localhost:3306/wallet
spring.datasource.username=david
spring.datasource.password=david
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jackson.time-zone=Africa/Nairobi
server.servlet.context-path=/konnect-wallet


#redis config
spring.data.redis.host=localhost
spring.data.redis.port=6379

spring.jpa.hibernate.ddl-auto=update
konnect.wallet.roles=User,Admim
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG

logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.springframework.security=DEBUG

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.api-docs.resolve-schema-properties=false
# Environment
ENVIROMENT=DEV

# JWT Configuration
JWT_SECRET=seccrettimessecrectminussecret
JWT_EXPIRY_TIME=7200000000000000
REFRESH_EXPRITY_TIME=51840000000000000
# Celcom Configuration
CELCOM_COOKIE=PHPSESSID=ss5984gkfpeauue7d102i9q56s
CELCOM_API_KEY=290c77e128c91b9f58435610082de01e
CELCOM_PARTNER_ID=5092
SMS_SENDER_ID=KONNECT
CELCOM_URL=https://mysms.celcomafrica.com

# OTP Configuration
#in seconds
OTP_TTL=300 
WINDOW_SIZE=60000

# Allowed IP Addresses
BANK_ALLOWED_IPS=13.245.135.143
WALLET_TEMPLATE_LOGIN=Your wallet Verification Code is
#Africas Talking
AFRICAS_TALKING_USERNAME=konnect
AFRICAS_TALKING_FROM=KONNECT
AFRICAS_TAKING_API_KEY=cd03e42b402660c70508040e0de61c7f52a6712ebe87746f4d413ccb83518304
AFRICAS_TAKING_URL=https://api.africastalking.com
# full package name of the class that implements SmsProvider
PRIMARY_SMS_PROVIDER=net.sasakonnect.wallet.provider.AfricasTalking 
className=net.sasakonnect.wallet.provider.Celcom,net.sasakonnect.wallet.provider.AfricasTalking
#
privateKey=eHQKJjjKtFwfnR05UN1vEH60-BaFciep0a08ydLnRkU3WH7p4aXLcpzLL0PXiaTG
CHOICE_SENDER=konnect



